// =============================================================================
// codegen command — generate TypeScript types from schema.json
// =============================================================================

import * as fs from "fs";
import * as path from "path";
import chalk from "chalk";
import { validateSchema, type SchemaInput } from "@plotpaper/core";

export async function runCodegen(target: string): Promise<void> {
  const resolved = path.resolve(target);

  if (!fs.existsSync(resolved) || !fs.statSync(resolved).isDirectory()) {
    console.error(chalk.red(`Not found or not a directory: ${resolved}`));
    process.exit(1);
  }

  const manifestPath = path.join(resolved, "plotpaper.json");
  if (!fs.existsSync(manifestPath)) {
    console.error(chalk.red(`No plotpaper.json found in ${resolved}`));
    console.error(chalk.dim(`  Run 'plotpaper init' to create a project.`));
    process.exit(1);
  }

  const schemaPath = path.join(resolved, "schema.json");
  if (!fs.existsSync(schemaPath)) {
    console.error(chalk.red(`No schema.json found in ${resolved}`));
    console.error(chalk.dim("  Create a schema.json with at least one entity to generate types."));
    process.exit(1);
  }

  let schema: SchemaInput;
  try {
    schema = validateSchema(fs.readFileSync(schemaPath, "utf-8"));
  } catch (e: any) {
    console.error(chalk.red(`\n  Schema error: ${e.message}`));
    process.exit(1);
  }

  if (schema.entities.length === 0) {
    console.log(chalk.yellow("\n  Schema has no entities — nothing to generate."));
    process.exit(0);
  }

  const output = generateTypes(schema);
  const outputPath = path.join(resolved, "plotpaper.generated.ts");
  fs.writeFileSync(outputPath, output, "utf-8");

  console.log(chalk.green.bold(`\n  ✓ Generated ${path.relative(process.cwd(), outputPath)}`));
  console.log(chalk.dim(`    ${schema.entities.length} entit${schema.entities.length === 1 ? "y" : "ies"}`));
  for (const entity of schema.entities) {
    console.log(chalk.dim(`    • ${pascalCase(singularize(entity.name))} (from ${entity.name})`));
  }
}

function generateTypes(schema: SchemaInput): string {
  const lines: string[] = [];

  lines.push("// Auto-generated by `plotpaper codegen` — do not edit");
  lines.push("// Source: schema.json");
  lines.push("");

  // Entity interfaces
  for (const entity of schema.entities) {
    const typeName = pascalCase(singularize(entity.name));
    lines.push(`export interface ${typeName} {`);
    lines.push(`  id: string;`);
    for (const attr of entity.attrs) {
      const tsType = mapValueType(attr.valueType);
      lines.push(`  ${attr.name}: ${tsType};`);
    }
    lines.push(`}`);
    lines.push("");
  }

  // DB map
  lines.push("/** Database entity map — keys are collection names, values are entity types */");
  lines.push("export interface DB {");
  for (const entity of schema.entities) {
    const typeName = pascalCase(singularize(entity.name));
    lines.push(`  ${entity.name}: ${typeName};`);
  }
  lines.push("}");
  lines.push("");

  // Query result helper
  lines.push("/**");
  lines.push(" * Typed query result. Usage:");
  lines.push(" *");
  lines.push(" * ```tsx");
  lines.push(" * const { isLoading, data } = sdk.db.useQuery({ todos: {} }) as QueryResult<\"todos\">;");
  lines.push(" * const todos = data?.todos ?? [];");
  lines.push(" * ```");
  lines.push(" */");
  lines.push("export type QueryResult<K extends keyof DB> = {");
  lines.push("  isLoading: boolean;");
  lines.push("  error: any;");
  lines.push("  data: { [P in K]: DB[P][] } | undefined;");
  lines.push("};");
  lines.push("");

  return lines.join("\n") + "\n";
}

function mapValueType(vt: string): string {
  switch (vt) {
    case "string":
      return "string";
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "date":
      return "string"; // InstantDB stores dates as ISO strings
    case "json":
      return "any";
    default:
      return "any";
  }
}

function pascalCase(str: string): string {
  return str.replace(/(^|[-_ ])(\w)/g, (_, __, c) => c.toUpperCase());
}

function singularize(str: string): string {
  if (str.endsWith("ies")) return str.slice(0, -3) + "y";
  if (str.endsWith("ses") || str.endsWith("xes") || str.endsWith("zes"))
    return str.slice(0, -2);
  if (str.endsWith("s") && !str.endsWith("ss")) return str.slice(0, -1);
  return str;
}
